version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - DB_URL=mongodb+srv://thamvarutwannachetisara:Thamvarut@hotel-booking.fnb37lo.mongodb.net/?retryWrites=true&w=majority&appName=Hotel-Booking
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - DB_URL=mongodb+srv://thamvarutwannachetisara:Thamvarut@hotel-booking.fnb37lo.mongodb.net/?retryWrites=true&w=majority&appName=Hotel-Booking
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017